Reindex annotated documents after annotation save, on update and create (#1308)
Princeton-CDH/geniza pull request #1309
Opened 2023-02-02 17:06 UTC by blms

## In this PR

Per #1308:
- On annotation update, wait until after annotation's `save()` method is called to reindex associated document, to ensure latest revision is in index
- On annotation creation, reindex associated document

2023-02-03 20:43 UTC, rlskoeser requested changes
Please implement using signal handlers like we do when other objects are updated; see the `index_depends_on` dict on `Document` and `DocumentSignalHandlers` in `geniza.corpus.models`

Now that annotation has foreign key access to documents through footnotes, it should work similarly to the other models — hopefully no code logic changes needed, just some dict entries and a queryset filter config. 

If the comments on that code isn't enough for you to figure it out efficiently, LMK

2023-02-06 17:05 UTC, blms commented
Good catch, thanks!

2023-02-06 17:59 UTC, rlskoeser approved these changes

2023-02-06 17:59 UTC, rlskoeser commented on geniza/corpus/models.py
> +        },
awesome that this is all it takes, glad the existing signal handler is working so well

2023-02-06 18:00 UTC, merged