Extending taggit.admin.TagAdmin to include document counts
Princeton-CDH/geniza pull request #970
Opened 2022-07-21 20:07 UTC by owenduffymassey

For [issue#909](https://github.com/Princeton-CDH/geniza/issues/909).  Let me know if there are any additional issues! Thanks for the help.

2022-07-21 20:26 UTC, owenduffymassey commented
Here is how my local setup runs tags with the document counts.
<img width="1466" alt="Screen Shot 2022-07-21 at 4 24 19 PM" src="https://user-images.githubusercontent.com/76797069/180308574-4d43bc46-e2cb-4d1b-9871-587ea6e06581.png">

2022-07-21 20:31 UTC, rlskoeser reviewed
Implementation looks good.

Please make the following changes:
- [ ] move the custom tag admin code to `geniza.common.admin` since it isn't specific to the corpus app (and we already have a lot of code in corpus admin)
- [ ] remove unneeded autocomplete exception in `get_queryset`
- [ ] write unit tests for the new methods (get queryset & document count); can probably adapt from similar tests in the corpus app

2022-07-21 20:31 UTC, rlskoeser commented on geniza/corpus/admin.py
> +            return qs
Did you test if taggit uses admin querysets for autocompletes? I think taggit probably custom autocomplete views, so these lines are unneeded.

2022-07-21 20:31 UTC, rlskoeser commented on geniza/corpus/admin.py
> +            document_count=Count("taggit_taggeditem_items", distinct=True),
Technically this is counting any tagged item, not just documents; we're only currently using tags for documents but I expect that to change in the future; so I suggest `item_count` for the field and `Count` for the label

2022-07-22 19:16 UTC, owenduffymassey commented
For the custom tag admin test, is it ok verify the item count number in the query set test? Also, what file should this test be in?

2022-07-22 19:45 UTC, rlskoeser commented
Hi @owenduffymassey 

> For the custom tag admin test, is it ok verify the item count number in the query set test? 

We run code coverage reports, so both of the methods you wrote should be tested (even though there is overlap). But that's the basic idea — create some test tags, call the queryset method, and confirm the counts are set as expected.

> Also, what file should this test be in?

Tests are organized by app, so these should be added to `geniza.common.tests`

2022-07-22 20:41 UTC, owenduffymassey commented
Ok great! Thanks for the help

2022-07-25 21:31 UTC, rlskoeser approved these changes

2022-07-25 21:35 UTC, rlskoeser requested changes
Ah, my apologies! I somehow missed that you opened your PR against `main`. We use git flow, so the PR needs to be to `develop`. I edited the PR to change the target but now it's including a bunch of irrelevant changes.

Would you please see if you can easily rebase your branch against current `develop` code? Or if that doesn't work, create a new branch based on `develop` and cherry-pick the commits from this branch.

Once that is resolved, this is ready to merge in and then I can deliver for acceptance testing.

2022-07-25 21:51 UTC, owenduffymassey commented
I just rebased my code against develop, should I continue by pushing with [`git push --force`](https://riptutorial.com/git/example/4357/pushing-after-a-rebase)?

2022-07-25 21:52 UTC, rlskoeser commented
> I just rebased my code against develop, should I continue by pushing with [`git push --force`](https://riptutorial.com/git/example/4357/pushing-after-a-rebase)?

yes, go ahead!

2022-07-25 23:02 UTC, owenduffymassey commented
I just pushed the new pull request against develop! For some reason the rebase wasn't working well for me.

2022-07-26 14:42 UTC, rlskoeser commented
cherry-picked into a fresh branch from develop and merged in via PR #981

2022-07-26 14:42 UTC, closed without merging